[Mysql]
MslUrl="127.0.0.1:3306"
MslUsername="root"
MslPasswd="123456"
MslName="db_node0"
MslProtocol="tcp"

[LogDB]
LogDBUrl="127.0.0.1:3306"
LogDBUsername="root"
LogDBPasswd="123456"
LogDBName="selflog_test"
LogDBProtocol="tcp"

[Canal]
CanalIP="127.0.0.1"
CanalPort=11111
CanalUsername="canal"
CanalPassword="canal"
CanalDestination="example"
CanalConnectedDB="db_node1"


[log]
Path="./"
